-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 13:55:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema email_validation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `email_validation` ;

-- -----------------------------------------------------
-- Schema email_validation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `email_validation` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `email_validation` ;

-- -----------------------------------------------------
-- Table `email_validation`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email_validation`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `email_validation`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `email_validation`.`users` (`id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
